# NumPy
 * NumPy provides efficient storage.
 * NumPy provides better ways of handling data for processing.
 * NumPy is fast and easy to learn.
 * NumPy uses relatively less memory to store data.


NumPy(Numerical Python) is a fundamental library for Python numerical computing. It provides efficient multi-dimensional array objects and various mathematical functions for handling large datasets making it a critical tool for professionals in fields that require heavy computation.

In [1]:
import numpy as np

In [2]:
myarr = np.array([3,45,69,25])

In [3]:
myarr

array([ 3, 45, 69, 25])

In [4]:
myarr[0]

np.int64(3)

In [5]:
my_arr = np.array([[3,45,69,25]])

In [6]:
my_arr[0,1]

np.int64(45)

In [7]:
my_arr = np.array([[3,45,69,25]], np.int64)

In [8]:
my_arr[0,1]

np.int64(45)

In [9]:
my_arr.shape

(1, 4)

In [10]:
my_arr.dtype

dtype('int64')

In [11]:
my_arr[0,1]=7

In [12]:
my_arr

array([[ 3,  7, 69, 25]])

> Array Creation

In [13]:
listarray = np.array([[1,2,3],[69,36,55],[7,18,45]])

In [14]:
listarray

array([[ 1,  2,  3],
       [69, 36, 55],
       [ 7, 18, 45]])

In [15]:
listarray.dtype

dtype('int64')

In [16]:
listarray.shape

(3, 3)

In [17]:
listarray.size

9

In [18]:
np.array({25,69,25})

array({25, 69}, dtype=object)

In [19]:
zero = np.zeros((3,6))

In [20]:
zero

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [21]:
zero.dtype

dtype('float64')

In [22]:
zero.shape

(3, 6)

In [23]:
rng = np.arange(21)

In [24]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

**linspace() function in NumPy returns an array of evenly spaced numbers over a specified range**

**np.linspace(start,end,no. of elements)**

In [25]:
lspace = np.linspace(1,10,5)

In [26]:
lspace

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [27]:
mt = np.empty((2,3))

In [28]:
mt

array([[-7.98962822e-312,  1.27757174e-061,  7.98977373e-312],
       [ 7.98977373e-312,  5.92878775e-323,  7.90505033e-323]])

In [29]:
mt_like = np.empty_like(lspace)

In [30]:
mt_like

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

***variable_name = np.identity(n) gives the nxn identity matrix***

In [31]:
ide = np.identity(5)

In [32]:
ide

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [33]:
ide.shape

(5, 5)

In [34]:
a=np.arange(20)

In [35]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

**From a given array we can convert into a matrix by reshape function**

**If we have mn no. of elements then we can form a m x n or n x m matrix**

In [36]:
a = a.reshape(5,4)

In [37]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

**From a matrix to a 1D array we use ravel function**

**Variable_name = present_matrix.ravel()** 

In [38]:
arr = a.ravel()

In [39]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [40]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

**1D array -- Axis0**

**2D array -- Axis0 for row and axis1 for column**

In [41]:
x = [[1,2,3],[4,5,6],[7,8,9]]

In [42]:
ar = np.array(x)

In [43]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [44]:
ar.sum(axis=0)

array([12, 15, 18])

**To find the sum of each row elements as per column we use array_name.sum(axis=0)**

In [45]:
ar.sum(axis=1)

array([ 6, 15, 24])

**To find the sum of each column elements as per row we use array_name.sum(axis=1)**

**To transpose an 2D array we have to use array_name.T**

In [46]:
ar.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [47]:
ar.flat

In [48]:
for item in ar:
    print(item)

[1 2 3]
[4 5 6]
[7 8 9]


In [49]:
for item in ar.flat:
    print(item)

1
2
3
4
5
6
7
8
9


**To show dimension use array_name.ndim**

In [50]:
ar.ndim

2

In [51]:
arr.ndim

1

**To find no of elements in array we use array_name.size**

In [52]:
ar.size

9

**Total bytes consumed by an array we use array_name.nbytes**

In [53]:
ar.nbytes

72

In [54]:
a.nbytes

160

In [55]:
one = np.array([18,77,7,45])

**To find max and min element in an 1D array we have to use array_name.argmax or array_name.argmin for the location of the min and max element and to find the value we have to use array_name.min or array_name.max**

In [56]:
one.argmin()

np.int64(2)

In [57]:
one.min()

np.int64(7)

In [58]:
one.argmax()

np.int64(1)

In [59]:
one.max()

np.int64(77)

**To sort the array index by value we have to use array_name.argsort**

In [60]:
one.argsort()

array([2, 0, 3, 1])

In [61]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [62]:
ar.argmin()

np.int64(0)

In [63]:
ar.argmax()

np.int64(8)

In [64]:
ar.argmax(axis=0)

array([2, 2, 2])

In [65]:
t = [[10,2,39],[42,55,6],[7,81,93]]

In [66]:
t

[[10, 2, 39], [42, 55, 6], [7, 81, 93]]

In [67]:
t = np.array(t)

In [68]:
t

array([[10,  2, 39],
       [42, 55,  6],
       [ 7, 81, 93]])

In [69]:
t.argmax()            # t.argmax() tells you where the largest value is located. Note: indexing starts from 0

np.int64(8)

In [70]:
t.argmin()            # t.argmin() tells you where the smallest value is located. Note: indexing starts from 0

np.int64(1)

In [71]:
t.argmax(axis=0)     # In each column, at which row is the maximum value. axis=0 means we’re working down each column (column-wise comparison).

array([1, 2, 2])

In [72]:
t.argmax(axis=1)    #In each row, at which column is the maximum value. axis=1 means we’re working across each row (row-wise comparison).

array([2, 1, 2])

In [73]:
t.argsort(axis=0)   # t.argsort(axis=0) returns the indices that would sort each column.If I sorted each column from top to bottom, what would be the row order.

array([[2, 0, 1],
       [0, 1, 0],
       [1, 2, 2]])

In [74]:
t.argsort(axis=1)    # t.argsort(axis=1) returns the indices that would sort each row.If I sorted each row from left to right, what would be the column order.

array([[1, 0, 2],
       [2, 0, 1],
       [0, 1, 2]])

In [75]:
t.ravel()         # returns a 1D (flattened) view of the array t.

array([10,  2, 39, 42, 55,  6,  7, 81, 93])

In [76]:
t

array([[10,  2, 39],
       [42, 55,  6],
       [ 7, 81, 93]])

In [77]:
t_1 = np.array([[18,  1, 0],
       [40, 45,  7],
       [ 93, 9, 7]])

In [78]:
t_1

array([[18,  1,  0],
       [40, 45,  7],
       [93,  9,  7]])

**Matrix Addition**

In [79]:
t+t_1

array([[ 28,   3,  39],
       [ 82, 100,  13],
       [100,  90, 100]])

In [80]:
list = [1,2,3]

In [81]:
list_1 = [4,5,6]

In [82]:
list+list_1

[1, 2, 3, 4, 5, 6]

**Elementwise multiply**

In [83]:
t*t_1

array([[ 180,    2,    0],
       [1680, 2475,   42],
       [ 651,  729,  651]])

In [84]:
saq = np.array([[16,  1, 0],
       [40, 25,  49],
       [ 81, 9, 7]])

In [85]:
saq

array([[16,  1,  0],
       [40, 25, 49],
       [81,  9,  7]])

**Elementwise Square root**

In [86]:
np.sqrt(saq)

array([[4.        , 1.        , 0.        ],
       [6.32455532, 5.        , 7.        ],
       [9.        , 3.        , 2.64575131]])

In [87]:
n = np.array([[6,  1, 0],
       [4, 5,  0],
       [ 8, 10, 2]])

In [88]:
n

array([[ 6,  1,  0],
       [ 4,  5,  0],
       [ 8, 10,  2]])

**Sum of all the elements of the array**

In [89]:
n.sum()

np.int64(36)

In [90]:
n.max()

np.int64(10)

In [91]:
np.where(n>7)

(array([2, 2]), array([0, 1]))

**Count no of non-zero element**

In [92]:
np.count_nonzero(n)

7

**Where non-zero elements are presents. For every non-zero element each axis indices are in different tuples**

In [93]:
np.nonzero(n)

(array([0, 0, 1, 1, 2, 2, 2]), array([0, 1, 0, 1, 0, 1, 2]))

In [94]:
import sys

In [95]:
py_ar = [18,45,7,93]

In [96]:
np_ar = np.array(py_ar)

In [97]:
py_ar

[18, 45, 7, 93]

In [98]:
np_ar

array([18, 45,  7, 93])

In [99]:
sys.getsizeof(1)*len(py_ar)

112

In [100]:
np_ar.itemsize*np_ar.size

32

**Dot product of two arrays**

In [101]:
u = np.array([1,2,3])

In [102]:
v = np.array([4,5,6])

In [103]:
u

array([1, 2, 3])

In [104]:
v

array([4, 5, 6])

In [105]:
np.dot(u,v)

np.int64(32)

In [106]:
u.tolist()

[1, 2, 3]

In [107]:
x = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])

In [108]:
y = np.array([[1,7,10],
              [12,42,96],
              [18,45,93]])

In [109]:
np.dot(x,y)

array([[  79,  226,  481],
       [ 172,  508, 1078],
       [ 265,  790, 1675]])